#define SFML_STATIC

#ifdef _DEBUG
#pragma comment(lib, "C:/SFML/lib/sfml-system-s-d.lib")
#pragma comment(lib, "C:/SFML/lib/sfml-window-s-d.lib")
#pragma comment(lib, "C:/SFML/lib/sfml-graphics-s-d.lib")
#else
#pragma comment(lib, "C:/SFML/lib/sfml-system-s.lib")
#pragma comment(lib, "C:/SFML/lib/sfml-window-s.lib")
#pragma comment(lib, "C:/SFML/lib/sfml-graphics-s.lib")
#endif
#pragma comment(lib, "C:/SFML/lib/freetype.lib")
#pragma comment(lib, "winmm.lib")
#pragma comment(lib, "opengl32.lib")
#pragma comment(lib, "gdi32.lib")

#pragma include_alias(<SFML/Audio.hpp>,						<C:/SFML/include/SFML/Audio.hpp>)
#pragma include_alias(<SFML/Audio/AlResource.hpp>,			<C:/SFML/include/SFML/Audio/AlResource.hpp>)
#pragma include_alias(<SFML/Audio/Export.hpp>,				<C:/SFML/include/SFML/Audio/Export.hpp>)
#pragma include_alias(<SFML/Audio/InputSoundFile.hpp>,		<C:/SFML/include/SFML/Audio/InputSoundFile.hpp>)
#pragma include_alias(<SFML/Audio/Listener.hpp>,			<C:/SFML/include/SFML/Audio/Listener.hpp>)
#pragma include_alias(<SFML/Audio/Music.hpp>,				<C:/SFML/include/SFML/Audio/Music.hpp>)
#pragma include_alias(<SFML/Audio/OutputSoundFile.hpp>,		<C:/SFML/include/SFML/Audio/OutputSoundFile.hpp>)
#pragma include_alias(<SFML/Audio/Sound.hpp>,				<C:/SFML/include/SFML/Audio/Sound.hpp>)
#pragma include_alias(<SFML/Audio/SoundBuffer.hpp>,			<C:/SFML/include/SFML/Audio/SoundBuffer.hpp>)
#pragma include_alias(<SFML/Audio/SoundBufferRecorder.hpp>,	<C:/SFML/include/SFML/Audio/SoundBufferRecorder.hpp>)
#pragma include_alias(<SFML/Audio/SoundFileFactory.hpp>,	<C:/SFML/include/SFML/Audio/SoundFileFactory.hpp>)
#pragma include_alias(<SFML/Audio/SoundFileFactory.inl>,	<C:/SFML/include/SFML/Audio/SoundFileFactory.inl>)
#pragma include_alias(<SFML/Audio/SoundFileReader.hpp>,		<C:/SFML/include/SFML/Audio/SoundFileReader.hpp>)
#pragma include_alias(<SFML/Audio/SoundFileWriter.hpp>,		<C:/SFML/include/SFML/Audio/SoundFileWriter.hpp>)
#pragma include_alias(<SFML/Audio/SoundRecorder.hpp>,		<C:/SFML/include/SFML/Audio/SoundRecorder.hpp>)
#pragma include_alias(<SFML/Audio/SoundSource.hpp>,			<C:/SFML/include/SFML/Audio/SoundSource.hpp>)
#pragma include_alias(<SFML/Audio/SoundStream.hpp>,			<C:/SFML/include/SFML/Audio/SoundStream.hpp>)

#pragma include_alias(<SFML/Config.hpp>,					<C:/SFML/include/SFML/Config.hpp>)
#pragma include_alias(<SFML/GpuPreference.hpp>,				<C:/SFML/include/SFML/GpuPreference.hpp>)

#pragma include_alias(<SFML/Graphics.hpp>,					<C:/SFML/include/SFML/Graphics.hpp>)
#pragma include_alias(<SFML/Graphics/BlendMode.hpp>,		<C:/SFML/include/SFML/Graphics/BlendMode.hpp>)
#pragma include_alias(<SFML/Graphics/CircleShape.hpp>,		<C:/SFML/include/SFML/Graphics/CircleShape.hpp>)
#pragma include_alias(<SFML/Graphics/Color.hpp>,			<C:/SFML/include/SFML/Graphics/Color.hpp>)
#pragma include_alias(<SFML/Graphics/ConvexShape.hpp>,		<C:/SFML/include/SFML/Graphics/ConvexShape.hpp>)
#pragma include_alias(<SFML/Graphics/Drawable.hpp>,			<C:/SFML/include/SFML/Graphics/Drawable.hpp>)
#pragma include_alias(<SFML/Graphics/Export.hpp>,			<C:/SFML/include/SFML/Graphics/Export.hpp>)
#pragma include_alias(<SFML/Graphics/Font.hpp>,				<C:/SFML/include/SFML/Graphics/Font.hpp>)
#pragma include_alias(<SFML/Graphics/Glsl.hpp>,				<C:/SFML/include/SFML/Graphics/Glsl.hpp>)
#pragma include_alias(<SFML/Graphics/Glsl.inl>,				<C:/SFML/include/SFML/Graphics/Glsl.inl>)
#pragma include_alias(<SFML/Graphics/Glyph.hpp>,			<C:/SFML/include/SFML/Graphics/Glyph.hpp>)
#pragma include_alias(<SFML/Graphics/Image.hpp>,			<C:/SFML/include/SFML/Graphics/Image.hpp>)
#pragma include_alias(<SFML/Graphics/PrimitiveType.hpp>,	<C:/SFML/include/SFML/Graphics/PrimitiveType.hpp>)
#pragma include_alias(<SFML/Graphics/Rect.hpp>,				<C:/SFML/include/SFML/Graphics/Rect.hpp>)
#pragma include_alias(<SFML/Graphics/Rect.inl>,				<C:/SFML/include/SFML/Graphics/Rect.inl>)
#pragma include_alias(<SFML/Graphics/RectangleShape.hpp>,	<C:/SFML/include/SFML/Graphics/RectangleShape.hpp>)
#pragma include_alias(<SFML/Graphics/RenderStates.hpp>,		<C:/SFML/include/SFML/Graphics/RenderStates.hpp>)
#pragma include_alias(<SFML/Graphics/RenderTarget.hpp>,		<C:/SFML/include/SFML/Graphics/RenderTarget.hpp>)
#pragma include_alias(<SFML/Graphics/RenderTexture.hpp>,	<C:/SFML/include/SFML/Graphics/RenderTexture.hpp>)
#pragma include_alias(<SFML/Graphics/RenderWindow.hpp>,		<C:/SFML/include/SFML/Graphics/RenderWindow.hpp>)
#pragma include_alias(<SFML/Graphics/Shader.hpp>,			<C:/SFML/include/SFML/Graphics/Shader.hpp>)
#pragma include_alias(<SFML/Graphics/Shape.hpp>,			<C:/SFML/include/SFML/Graphics/Shape.hpp>)
#pragma include_alias(<SFML/Graphics/Sprite.hpp>,			<C:/SFML/include/SFML/Graphics/Sprite.hpp>)
#pragma include_alias(<SFML/Graphics/Text.hpp>,				<C:/SFML/include/SFML/Graphics/Text.hpp>)
#pragma include_alias(<SFML/Graphics/Texture.hpp>,			<C:/SFML/include/SFML/Graphics/Texture.hpp>)
#pragma include_alias(<SFML/Graphics/Transform.hpp>,		<C:/SFML/include/SFML/Graphics/Transform.hpp>)
#pragma include_alias(<SFML/Graphics/Transformable.hpp>,	<C:/SFML/include/SFML/Graphics/Transformable.hpp>)
#pragma include_alias(<SFML/Graphics/Vertex.hpp>,			<C:/SFML/include/SFML/Graphics/Vertex.hpp>)
#pragma include_alias(<SFML/Graphics/VertexArray.hpp>,		<C:/SFML/include/SFML/Graphics/VertexArray.hpp>)
#pragma include_alias(<SFML/Graphics/VertexBuffer.hpp>,		<C:/SFML/include/SFML/Graphics/VertexBuffer.hpp>)
#pragma include_alias(<SFML/Graphics/View.hpp>,				<C:/SFML/include/SFML/Graphics/View.hpp>)

#pragma include_alias(<SFML/Main.hpp>,						<C:/SFML/include/SFML/Main.hpp>)

#pragma include_alias(<SFML/Network.hpp>,					<C:/SFML/include/SFML/Network.hpp>)
#pragma include_alias(<SFML/Network/Export.hpp>,			<C:/SFML/include/SFML/Network/Export.hpp>)
#pragma include_alias(<SFML/Network/Ftp.hpp>,				<C:/SFML/include/SFML/Network/Ftp.hpp>)
#pragma include_alias(<SFML/Network/Http.hpp>,				<C:/SFML/include/SFML/Network/Http.hpp>)
#pragma include_alias(<SFML/Network/IpAddress.hpp>,			<C:/SFML/include/SFML/Network/IpAddress.hpp>)
#pragma include_alias(<SFML/Network/Packet.hpp>,			<C:/SFML/include/SFML/Network/Packet.hpp>)
#pragma include_alias(<SFML/Network/Socket.hpp>,			<C:/SFML/include/SFML/Network/Socket.hpp>)
#pragma include_alias(<SFML/Network/SocketHandle.hpp>,		<C:/SFML/include/SFML/Network/SocketHandle.hpp>)
#pragma include_alias(<SFML/Network/SocketSelector.hpp>,	<C:/SFML/include/SFML/Network/SocketSelector.hpp>)
#pragma include_alias(<SFML/Network/TcpListener.hpp>,		<C:/SFML/include/SFML/Network/TcpListener.hpp>)
#pragma include_alias(<SFML/Network/TcpSocket.hpp>,			<C:/SFML/include/SFML/Network/TcpSocket.hpp>)
#pragma include_alias(<SFML/Network/UdpSocket.hpp>,			<C:/SFML/include/SFML/Network/UdpSocket.hpp>)

#pragma include_alias(<SFML/OpenGL.hpp>,					<C:/SFML/include/SFML/OpenGL.hpp>)

#pragma include_alias(<SFML/System.hpp>,					<C:/SFML/include/SFML/System.hpp>)
#pragma include_alias(<SFML/System/Clock.hpp>,				<C:/SFML/include/SFML/System/Clock.hpp>)
#pragma include_alias(<SFML/System/Err.hpp>,				<C:/SFML/include/SFML/System/Err.hpp>)
#pragma include_alias(<SFML/System/Export.hpp>,				<C:/SFML/include/SFML/System/Export.hpp>)
#pragma include_alias(<SFML/System/FileInputStream.hpp>,	<C:/SFML/include/SFML/System/FileInputStream.hpp>)
#pragma include_alias(<SFML/System/InputStream.hpp>,		<C:/SFML/include/SFML/System/InputStream.hpp>)
#pragma include_alias(<SFML/System/Lock.hpp>,				<C:/SFML/include/SFML/System/Lock.hpp>)
#pragma include_alias(<SFML/System/MemoryInputStream.hpp>,	<C:/SFML/include/SFML/System/MemoryInputStream.hpp>)
#pragma include_alias(<SFML/System/Mutex.hpp>,				<C:/SFML/include/SFML/System/Mutex.hpp>)
#pragma include_alias(<SFML/System/NativeActivity.hpp>,		<C:/SFML/include/SFML/System/NativeActivity.hpp>)
#pragma include_alias(<SFML/System/NonCopyable.hpp>,		<C:/SFML/include/SFML/System/NonCopyable.hpp>)
#pragma include_alias(<SFML/System/Sleep.hpp>,				<C:/SFML/include/SFML/System/Sleep.hpp>)
#pragma include_alias(<SFML/System/String.hpp>,				<C:/SFML/include/SFML/System/String.hpp>)
#pragma include_alias(<SFML/System/String.inl>,				<C:/SFML/include/SFML/System/String.inl>)
#pragma include_alias(<SFML/System/Thread.hpp>,				<C:/SFML/include/SFML/System/Thread.hpp>)
#pragma include_alias(<SFML/System/Thread.inl>,				<C:/SFML/include/SFML/System/Thread.inl>)
#pragma include_alias(<SFML/System/ThreadLocal.hpp>,		<C:/SFML/include/SFML/System/ThreadLocal.hpp>)
#pragma include_alias(<SFML/System/ThreadLocalPtr.hpp>,		<C:/SFML/include/SFML/System/ThreadLocalPtr.hpp>)
#pragma include_alias(<SFML/System/ThreadLocalPtr.inl>,		<C:/SFML/include/SFML/System/ThreadLocalPtr.inl>)
#pragma include_alias(<SFML/System/Time.hpp>,				<C:/SFML/include/SFML/System/Time.hpp>)
#pragma include_alias(<SFML/System/Utf.hpp>,				<C:/SFML/include/SFML/System/Utf.hpp>)
#pragma include_alias(<SFML/System/Utf.inl>,				<C:/SFML/include/SFML/System/Utf.inl>)
#pragma include_alias(<SFML/System/Vector2.hpp>,			<C:/SFML/include/SFML/System/Vector2.hpp>)
#pragma include_alias(<SFML/System/Vector2.inl>,			<C:/SFML/include/SFML/System/Vector2.inl>)
#pragma include_alias(<SFML/System/Vector3.hpp>,			<C:/SFML/include/SFML/System/Vector3.hpp>)
#pragma include_alias(<SFML/System/Vector3.inl>,			<C:/SFML/include/SFML/System/Vector3.inl>)

#pragma include_alias(<SFML/Window.hpp>,					<C:/SFML/include/SFML/Window.hpp>)
#pragma include_alias(<SFML/Window/Clipboard.hpp>,			<C:/SFML/include/SFML/Window/Clipboard.hpp>)
#pragma include_alias(<SFML/Window/Context.hpp>,			<C:/SFML/include/SFML/Window/Context.hpp>)
#pragma include_alias(<SFML/Window/ContextSettings.hpp>,	<C:/SFML/include/SFML/Window/ContextSettings.hpp>)
#pragma include_alias(<SFML/Window/Cursor.hpp>,				<C:/SFML/include/SFML/Window/Cursor.hpp>)
#pragma include_alias(<SFML/Window/Event.hpp>,				<C:/SFML/include/SFML/Window/Event.hpp>)
#pragma include_alias(<SFML/Window/Export.hpp>,				<C:/SFML/include/SFML/Window/Export.hpp>)
#pragma include_alias(<SFML/Window/GlResource.hpp>,			<C:/SFML/include/SFML/Window/GlResource.hpp>)
#pragma include_alias(<SFML/Window/Joystick.hpp>,			<C:/SFML/include/SFML/Window/Joystick.hpp>)
#pragma include_alias(<SFML/Window/Keyboard.hpp>,			<C:/SFML/include/SFML/Window/Keyboard.hpp>)
#pragma include_alias(<SFML/Window/Mouse.hpp>,				<C:/SFML/include/SFML/Window/Mouse.hpp>)
#pragma include_alias(<SFML/Window/Sensor.hpp>,				<C:/SFML/include/SFML/Window/Sensor.hpp>)
#pragma include_alias(<SFML/Window/Touch.hpp>,				<C:/SFML/include/SFML/Window/Touch.hpp>)
#pragma include_alias(<SFML/Window/VideoMode.hpp>,			<C:/SFML/include/SFML/Window/VideoMode.hpp>)
#pragma include_alias(<SFML/Window/Vulkan.hpp>,				<C:/SFML/include/SFML/Window/Vulkan.hpp>)
#pragma include_alias(<SFML/Window/Window.hpp>,				<C:/SFML/include/SFML/Window/Window.hpp>)
#pragma include_alias(<SFML/Window/WindowBase.hpp>,			<C:/SFML/include/SFML/Window/WindowBase.hpp>)
#pragma include_alias(<SFML/Window/WindowHandle.hpp>,		<C:/SFML/include/SFML/Window/WindowHandle.hpp>)
#pragma include_alias(<SFML/Window/WindowStyle.hpp>,		<C:/SFML/include/SFML/Window/WindowStyle.hpp>)